# Assignment 1 — Python Fundamentals & NumPy

**Course:** Introduction to Data Science / Scientific Computing
**Topics:** Core Python, NumPy arrays, vectorization, broadcasting, linear algebra
**Total marks:** 50
**Time guideline:** 3–4 hours

---

### Instructions
1. Write your solution in the empty code cell directly **below each problem**.
2. Do **not** rename or delete the problem cells.
3. Your code must **run top to bottom without errors** (use *Kernel → Restart & Run All* before submitting).
4. Where a function is asked for, match the **exact function name and signature** given.
5. Comments explaining your logic are encouraged and count toward partial credit.
6. Submit this completed `.ipynb` file. Name it `assignment1_<your_name>.ipynb`.

> **Allowed imports:** only `numpy` (and the Python standard library). Do **not** use `pandas` for this assignment.


In [1]:
# Run this cell first
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.3.5


---
# Part A — Python Fundamentals  *(15 marks)*

No NumPy in this section. Plain Python only.

### A1. Temperature converter  *(2 marks)*

Write a function `c_to_f(celsius)` that converts a temperature in Celsius to Fahrenheit
using the formula `F = C * 9/5 + 32`.

- It should work for a single number **and** for a list of numbers (return a list in that case).

```python
c_to_f(0)          # -> 32.0
c_to_f(100)        # -> 212.0
c_to_f([0, 37, 100])  # -> [32.0, 98.6, 212.0]
```

In [1]:
# A1 — your solution here
def c_to_f(celsius):
    # If the input is a list, convert each element
    if isinstance(celsius, list): 
    #isinstance() checks if the input is a list
        
        new_list = [] 
        for c in celsius:
            new_list.append(c * 9/5 + 32)
            
        return new_list
         
    # For single number conversion
    else:
        return celsius * 9/5 + 32


choice = input("Enter 's' for single value or 'l' for list: ")
# Enters the user's choice as to convert a single data point or a number of such points in a list.
# The choice is converted to lowercase and then analyzed so as to determine the flow of the program.
if choice.lower() == 's':
    c = float(input("Enter temperature in Celsius: "))
    print("Temperature in Fahrenheit:", c_to_f(c))

elif choice.lower() == 'l':
    values = input("Enter Celsius values separated by spaces: ")
    c_list = [float(x) for x in values.split()]
    print("Temperatures in Fahrenheit:", c_to_f(c_list))

else:
    print("Invalid choice!")

Temperatures in Fahrenheit: [32.0, 77.0, 140.0, 89.6, 167.0]


### A2. FizzBuzz with a twist  *(3 marks)*

Write a function `fizzbuzz(n)` that returns a **list** of length `n` (covering numbers `1..n`) where:
- multiples of 3 are replaced by `"Fizz"`
- multiples of 5 are replaced by `"Buzz"`
- multiples of both 3 and 5 are replaced by `"FizzBuzz"`
- all other numbers stay as integers.

```python
fizzbuzz(5)  # -> [1, 2, 'Fizz', 4, 'Buzz']
```

In [2]:
# A2 — your solution here
def fizzbuzz(n):
    result = []

    for i in range(1, n + 1):

        if i % 3 == 0 and i % 5 == 0:
            result.append("FizzBuzz")

        elif i % 3 == 0:
            result.append("Fizz")

        elif i % 5 == 0:
            result.append("Buzz")

        else:
            result.append(i)

    return result


# User input
n = int(input("Enter a number: "))

print(fizzbuzz(n))

[1, 2, 'Fizz', 4, 'Buzz']


### A3. Word frequency counter  *(4 marks)*

Write a function `word_count(text)` that takes a string and returns a **dictionary** mapping each
lowercase word to the number of times it appears. Ignore case and strip basic punctuation (`. , ! ?`).

```python
word_count("The cat sat. The cat ran!")
# -> {'the': 2, 'cat': 2, 'sat': 1, 'ran': 1}
```

In [3]:
# A3 — your solution here
def word_count(text):

    # To convert the text to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.replace(".", "")
    text = text.replace(",", "")
    text = text.replace("!", "")
    text = text.replace("?", "")

    # Split the text into words
    words = text.split()

    # Create an empty dictionary
    count = {}

    # Count the occurrences of each word
    for i in words:
        if i in count:
            count[i] += 1
        else:
            count[i] = 1

    return count


# User input
text = input("Enter a sentence: ")

print(word_count(text))

{'we': 1, 'both': 1, 'looked': 2, 'into': 1, 'the': 2, 'abyss': 2, 'but': 1, 'when': 1, 'back': 1, 'at': 1, 'us': 1, 'you': 1, 'blinked': 1}


### A4. Filter and transform  *(3 marks)*

Given a list of integers, write a function `squares_of_evens(nums)` that returns a new list
containing the **squares of only the even numbers**, preserving order. Use a **list comprehension**.

```python
squares_of_evens([1, 2, 3, 4, 5, 6])  # -> [4, 16, 36]
```

In [4]:
# A4 — your solution here
def squares_of_evens(nums):
    return [num ** 2 for num in nums if num % 2 == 0]


# User input
values = input("Enter integers separated by spaces: ")
nums = []
y=values.split()
for x in y:
    nums.append(int(x))

print("Squares of even numbers:", squares_of_evens(nums))

Squares of even numbers: [4, 36, 64, 4, 36]


### A5. Running maximum  *(3 marks)*

Write a function `running_max(nums)` that returns a list where the element at index `i` is the
maximum of `nums[0..i]`. Solve it with a plain loop (no NumPy, no `max()` over slices).

```python
running_max([3, 1, 4, 1, 5, 9, 2, 6])  # -> [3, 3, 4, 4, 5, 9, 9, 9]
```

In [5]:
# A5 — your solution here
def running_max(nums):

    result = []            
    # List to store running maximums
    current_max = nums[0]  
    # Assuming the first element to be the maximum

    for i in nums:
        if i > current_max:
            current_max = i

        result.append(current_max)

    return result


# User input
values = input("Enter integers separated by spaces: ")
nums= []
y=values.split()
for x in y:
    nums.append(int(x))


print("Running maximum:", running_max(nums))

Running maximum: [5, 6, 9, 9, 9, 9, 9, 9, 14, 14, 14, 14]


---
# Part B — NumPy Core  *(25 marks)*

From here on, prefer **vectorized NumPy operations** over Python loops unless a loop is explicitly allowed.

### B1. Array creation  *(3 marks)*

Create and print the following arrays. Assign each to the variable name shown.

1. `a` — a 1-D array of the integers from 10 to 20 **inclusive**.
2. `b` — a 3×3 array of all ones, dtype `float`.
3. `c` — a 1-D array of 9 values **evenly spaced** between 0 and 1 (inclusive of both ends).
4. `d` — a 4×4 identity matrix.

In [6]:
# B1 — your solution here
import numpy as np

# 1. a — integers from 10 to 20 inclusive
a = np.arange(10, 21)

# 2. b — 3×3 array of ones, dtype float
b = np.ones((3, 3), dtype=float)

# 3. c — 9 evenly spaced values between 0 and 1 inclusive
c = np.linspace(0, 1, 9)

# 4. d — 4×4 identity matrix
d = np.eye(4)

# Print the arrays
print("a =\n", a)
print("\nb =\n", b)
print("\nc =\n", c)
print("\nd =\n", d)

a =
 [10 11 12 13 14 15 16 17 18 19 20]

b =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

c =
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]

d =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### B2. Indexing & slicing  *(4 marks)*

Given the array `M` below, use slicing/indexing (no loops) to produce:

1. `r2` — the **third row**.
2. `last_col` — the **last column**.
3. `block` — the top-left **2×2** sub-matrix.
4. `every_other` — every other element of the **flattened** array (elements 0, 2, 4, ...).

In [7]:

# B2 — your solution here
import numpy as np
M = np.arange(1, 26).reshape(5, 5)
print(M)
# 1. Third row
r2 = M[2]

# 2. Last column
last_col = M[:, -1]

# 3. Top-left 2×2 sub-matrix
block = M[:2, :2]

# 4. Every other element of the flattened array
every_other = M.flatten()[::2]

print("Third row:")
print(r2)

print("\nLast column:")
print(last_col)

print("\nTop-left 2x2 block:")
print(block)

print("\nEvery other element of the flattened array:")
print(every_other)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Third row:
[11 12 13 14 15]

Last column:
[ 5 10 15 20 25]

Top-left 2x2 block:
[[1 2]
 [6 7]]

Every other element of the flattened array:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


### B3. Loops vs vectorization  *(4 marks)*

You are given `x = np.arange(1, 1_000_001)`.

1. Write a function `sum_of_squares_loop(x)` that computes the sum of squares using a **Python `for` loop**.
2. Write a function `sum_of_squares_vec(x)` that computes the same thing using **vectorized NumPy**.
3. Confirm both give the same result.
4. Use `%timeit` (or `time`) to compare their speed and briefly comment in a comment line on what you observe.

In [8]:
# B3 — your solution here
import numpy as np
import time

# Create the array
x = np.arange(1, 1_000_001)

# Function using a Python for loop
def sum_of_squares_loop(x):
    total = 0
    for i in x:
        total += i ** 2
    return total

# Function using vectorized NumPy
def sum_of_squares_vec(x):
    return np.sum(x ** 2)

# Confirm both give the same result
result_loop = sum_of_squares_loop(x)
result_vec = sum_of_squares_vec(x)

print("Loop result      :", result_loop)
print("Vectorized result:", result_vec)
print("Same result?     :", result_loop == result_vec)

# Time the loop version
start = time.time()
sum_of_squares_loop(x)
end = time.time()
print("Loop time:", end - start, "seconds")

# Time the vectorized version
start = time.time()
sum_of_squares_vec(x)
end = time.time()
print("Vectorized time:", end - start, "seconds")

#The vectorized NumPy implementation is much faster than the Python loop version

Loop result      : 333333833333500000
Vectorized result: 333333833333500000
Same result?     : True
Loop time: 0.10720467567443848 seconds
Vectorized time: 0.003275632858276367 seconds


### B4. Aggregations along an axis  *(4 marks)*

Given a 2-D array `scores` of shape (5 students, 4 subjects):

1. `student_avg` — each student's average score (length-5 array).
2. `subject_max` — the highest score in each subject (length-4 array).
3. `top_student` — the **index** of the student with the highest total.
4. `overall_std` — the standard deviation of all scores.

In [9]:

# B4 — your solution here
import numpy as np

rng = np.random.default_rng(42)
scores = rng.integers(40, 101, size=(5, 4))
print(scores)

# B4 — your solution here

# 1. Average score of each student
student_avg = np.mean(scores, axis=1)

# 2. Highest score in each subject
subject_max = np.max(scores, axis=0)

# 3. Index of the student with the highest total score
top_student = np.argmax(np.sum(scores, axis=1))

# 4. Standard deviation of all scores
overall_std = np.std(scores)

print("Student averages:", student_avg)
print("Subject maximums:", subject_max)
print("Top student index:", top_student)
print("Overall standard deviation:", overall_std)

[[45 87 79 66]
 [66 92 45 82]
 [52 45 72 99]
 [84 86 83 87]
 [71 47 91 67]]
Student averages: [69.25 71.25 67.   85.   69.  ]
Subject maximums: [84 92 91 99]
Top student index: 3
Overall standard deviation: 17.11461363864227


### B5. Boolean masking  *(4 marks)*

Using the `scores` array from B4:

1. `passing` — a boolean array, `True` where score >= 60.
2. `num_passing` — total count of passing scores.
3. `high_scores` — a 1-D array of all scores strictly greater than 90.
4. Replace every score below 50 with 50 (a "grade floor"), storing the result in `floored` **without modifying** `scores`.

In [10]:
# B5 — your solution here
import numpy as np

# Using the scores array from B4

# 1. Boolean array: True where score >= 60
passing = scores >= 60

# 2. Total number of passing scores
num_passing = np.sum(passing)

# 3. 1-D array of all scores greater than 90
high_scores = scores[scores > 90]

# 4. Replace scores below 50 with 50 without modifying the original array
floored = np.where(scores < 50, 50, scores)

print("Passing:")
print(passing)

print("\nNumber of passing scores:", num_passing)

print("\nHigh scores (>90):")
print(high_scores)

print("\nFloored scores:")
print(floored)

Passing:
[[False  True  True  True]
 [ True  True False  True]
 [False False  True  True]
 [ True  True  True  True]
 [ True False  True  True]]

Number of passing scores: 15

High scores (>90):
[92 99 91]

Floored scores:
[[50 87 79 66]
 [66 92 50 82]
 [52 50 72 99]
 [84 86 83 87]
 [71 50 91 67]]


### B6. Reshaping & broadcasting  *(3 marks)*

1. Take `np.arange(12)` and reshape it into a 3×4 array called `grid`.
2. Create a 1-D array `col_weights = np.array([1, 2, 3, 4])` and multiply each **column** of `grid`
   by the corresponding weight using **broadcasting** (no loops). Store as `weighted`.
3. Subtract the **row mean** from each element so every row of `centered` has mean 0.

In [11]:
# B6 — your solution here
import numpy as np

# 1. Create the grid
grid = np.arange(12).reshape(3, 4)

# 2. Apply column weights using broadcasting
col_weights = np.array([1, 2, 3, 4])
weighted = grid * col_weights

# 3. Subtract the row mean from each row
centered = weighted - weighted.mean(axis=1, keepdims=True)

print("grid:\n", grid)
print("\nweighted:\n", weighted)
print("\ncentered:\n", centered)

grid:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

weighted:
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]

centered:
 [[ -5.  -3.   1.   7.]
 [-11.  -5.   3.  13.]
 [-17.  -7.   5.  19.]]


### B7. Linear algebra  *(3 marks)*

Solve the system of linear equations:

```
2x +  y -  z =  8
-3x - y + 2z = -11
-2x + y + 2z =  -3
```

1. Build the coefficient matrix `A` and the right-hand side vector `b`.
2. Solve for `[x, y, z]` using `np.linalg.solve` and store as `solution`.
3. Verify by computing `A @ solution` and comparing to `b` (use `np.allclose`).

In [12]:
# B7 — your solution here
import numpy as np

# 1. Coefficient matrix A and RHS vector b
A = np.array([
    [ 2,  1, -1],
    [-3, -1,  2],
    [-2,  1,  2]])

b = np.array([8, -11, -3])

# 2. Solve the system
solution = np.linalg.solve(A, b)

print("Solution:", solution)

# 3. Verify the solution
verification = A @ solution
print("A @ solution =", verification)
print("Matches b:", np.allclose(verification, b))

Solution: [ 2.  3. -1.]
A @ solution = [  8. -11.  -3.]
Matches b: True


---
# Part C — Applied Mini-Problem  *(10 marks)*

### C1. Monte Carlo estimate of π  *(6 marks)*

You can estimate π by throwing random darts at a unit square `[0,1] x [0,1]` and counting how many
land inside the quarter circle of radius 1 centered at the origin. The fraction inside, times 4,
approximates π.

Write a function `estimate_pi(n, seed=0)` that:
1. Generates `n` random `(x, y)` points in the unit square using a seeded `np.random.default_rng`.
2. Counts how many fall inside the quarter circle (`x**2 + y**2 <= 1`) — **vectorized, no loops**.
3. Returns the estimate of π as a float.

Then call it with `n = 1_000_000` and print your estimate alongside `np.pi`.

In [13]:
# C1 — your solution here
import numpy as np

def estimate_pi(n, seed=0):
    rng = np.random.default_rng(seed)

    # Generate n random (x, y) points in [0,1] x [0,1]
    points = rng.random((n, 2))
    x = points[:, 0]
    y = points[:, 1]

    # Count points inside the quarter circle
    inside = (x**2 + y**2) <= 1

    # Estimate π
    return 4 * np.mean(inside)

# Run the simulation
n = 1_000_000
pi_estimate = estimate_pi(n)

print("Estimated π:", pi_estimate)
print("NumPy π:     ", np.pi)
print("Error:       ", abs(pi_estimate - np.pi))

Estimated π: 3.141168
NumPy π:      3.141592653589793
Error:        0.0004246535897931558


### C2. Short reflection  *(4 marks)*

In the markdown cell below, answer in 3–5 sentences:

1. Why is the vectorized NumPy version in B3 so much faster than the Python loop?
2. How does the accuracy of your π estimate in C1 change as `n` grows, and why?

*Write your answer here (double-click to edit).*

1. The vectorized NumPy version is much faster because the calculations are carried out in optimized, compiled C code rather than in the Python interpreter. In the loop version, Python executes each iteration at a time. For each variable, python must retrieve the value, perform the exponentiation, perform the addition, update the variable and repeat the process 1,00,000 times. NumPy performs operations on entire arrays, using higly optimized routines compiled in C code, which executes much faster than Python.

2. Since the estimate is based on the fraction of randomly generated points that fall inside the quarter circle, and each point is an independent random sample, so by the Law of Large Numbers, the observed fraction converges to the true probability as the number of samples increases. The standard error of a Monte Carlo estimate is inversely proportional to the square root of n. The estimates fluctuate randomly around π, but the fluctuations become smaller as n increases.

---
### Before you submit — checklist
- [ ] Restart kernel and *Run All* — no errors.
- [ ] All function names and signatures match the spec exactly.
- [ ] No use of `pandas`; only `numpy` and the standard library.
- [ ] File renamed to `assignment1_<your_name>.ipynb`.

*Good luck!*